server:
  mode: "dev"
  scheme: "http"
  domain: "localhost"

port: 50090
serviceName: "services"

email:
  server: "smtp.gmail.com"
  port: 587
  user: "unona.tech@gmail.com"
  pass: "cghmcvxcgkaunvft"
  admin: "jmurvz@gmail.com"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "services_db"

redis:
  addr: "localhost:6379"
  pass: ""

kafka:
  addrs: [ "localhost:9092" ]
  notificationTopic: "notifications"
  verificationEmailTopic: "verification_user_email"
  loginEmailTopic: "login_email"
  activationCodeEmailTopic: "activation_code_email"
  forgotPasswordEmailTopic: "forgot_password_email"

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "localhost:6831"